[package]
name = "xenon-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
prost.workspace = true
rcgen.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
toml.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
xenon-domain = { path = "../domain" }
xenon-protocol = { path = "../protocol" }
xray-embedded-runner = { path = "../xray-runner" }
xray-core-protocol = { path = "../xray-protocol" }

[dev-dependencies]
tempfile = "3"
