[package]
name = "xenon-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
xenon-domain = { path = "../domain" }

[dev-dependencies]
tempfile = "3"
